#!/usr/bin/env python3
"""
Turn CLINC150 into a training file for a chosen set of intents.

CLINC150 labels *intents*, not replies, so the mapping from intent to the terse
string the model should emit is ours to author - that is what a RECIPE is.  Keep
replies short and sharing letters: the charset is the output layer, and every
distinct character costs 128 weights.

    python data/clinc150/subset.py --recipe smalltalk > out.txt
    python data/clinc150/subset.py --list           # every available intent
    python data/lint.py out.txt --strict

150 intents is far more than a 2-bit model can learn, so a recipe picks a
handful.  `oos` is CLINC's own out-of-scope class - 1,200 utterances of things a
system cannot answer - which is a much better catch-all than invented nonsense.
"""

from __future__ import annotations

import argparse
import gzip
import json
import random
import sys
from pathlib import Path

DATA = Path(__file__).with_name('data_full.json.gz')

#: name -> {intent: reply}.  Add recipes here rather than editing one in place;
#: a shipped example depends on its recipe staying put.
RECIPES: dict[str, dict[str, str]] = {
    # The chatbot register: what someone types at a toy that talks back.
    'smalltalk': {
        'greeting': 'HI',
        'goodbye': 'BYE',
        'thank_you': 'NO PROB',
        'yes': 'OK',
        'no': 'NOPE',
        'maybe': 'MAYBE',
        'are_you_a_bot': 'IM A BOT',
        'what_is_your_name': 'IM CHAT',
        'how_old_are_you': 'OLD',
        'where_are_you_from': 'A ROM CHIP',
        'who_made_you': 'A HUMAN',
        'what_are_your_hobbies': 'BITS',
        'do_you_have_pets': 'NO PETS',
        'tell_joke': 'HA HA',
        'fun_fact': 'HMM',
        'meaning_of_life': 'WHO KNOWS',
        'what_can_i_ask_you': 'ASK ME',
        'repeat': 'AGAIN',
        'oos': 'IDK',
    },
}


def load() -> list[tuple[str, str]]:
    """Every (utterance, intent) pair, across all of CLINC's splits.

    The published train/val/test split is not used: feedme does its own, by
    unique query, and mixing the splits here would only hide that.
    """
    with gzip.open(DATA, 'rt') as fh:
        data = json.load(fh)
    return [(q, label) for rows in data.values() for q, label in rows]


def build(recipe: dict[str, str], seed: int = 0,
          cap: int | None = None) -> list[tuple[str, str]]:
    """Balanced (query, reply) pairs for one recipe.

    Every in-scope intent ships exactly 150 utterances but `oos` ships 1,200,
    so without a cap the catch-all would be a third of the data and become the
    model's default answer.
    """
    by_intent: dict[str, set[str]] = {}
    for query, intent in load():
        if intent in recipe:
            by_intent.setdefault(intent, set()).add(query)

    missing = set(recipe) - set(by_intent)
    if missing:
        raise SystemExit(f"no such intent(s): {sorted(missing)}")

    in_scope = [len(v) for k, v in by_intent.items() if k != 'oos']
    if cap is None:
        cap = min(in_scope) if in_scope else max(map(len, by_intent.values()))

    rng = random.Random(seed)
    pairs: list[tuple[str, str]] = []
    for intent in sorted(by_intent):                 # sorted: reproducible
        queries = sorted(by_intent[intent])
        if len(queries) > cap:
            queries = rng.sample(queries, cap)
        pairs.extend((q.upper(), recipe[intent]) for q in queries)

    rng.shuffle(pairs)
    return pairs


def main() -> None:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument('--recipe', default='smalltalk', choices=sorted(RECIPES))
    parser.add_argument('--seed', type=int, default=0)
    parser.add_argument('--cap', type=int, default=None,
                        help='Max utterances per intent (default: the smallest '
                             'in-scope intent, so the classes come out balanced)')
    parser.add_argument('--list', action='store_true',
                        help='List every intent in the dataset and exit')
    args = parser.parse_args()

    if args.list:
        intents = sorted({intent for _, intent in load()})
        print(f"# {len(intents)} intents", file=sys.stderr)
        for intent in intents:
            print(intent)
        return

    recipe = RECIPES[args.recipe]
    pairs = build(recipe, args.seed, args.cap)

    print(f"# CLINC150, recipe '{args.recipe}', seed {args.seed}.")
    print("# Generated by data/clinc150/subset.py - do not edit by hand.")
    print(f"# {len(pairs)} pairs over {len(recipe)} replies.")
    print("# Source: https://github.com/clinc/oos-eval (CC BY 3.0), Larson et al.,")
    print("# EMNLP 2019. Utterances are uppercased; replies are ours.")
    for query, reply in pairs:
        print(f"{query}|{reply}")


if __name__ == '__main__':
    main()
