#!/usr/bin/env python3
"""
What a corpus costs as it grows, measured at four sizes instead of reasoned
from one.

    python data/silo/sweep.py                        # ~7 minutes
    python data/silo/sweep.py --people 5000,10000    # quicker

`benchcard.py` measures one card in depth. This measures several shallowly,
because two of the questions in issue #62 are about the slope rather than the
value, and a single corpus cannot show a slope.

## Whether a query gets dearer as the corpus grows

`data/wikipedia/README.md` and `data/silo/README.md` both conclude that what
sets the price of a query is how widely one term's postings scatter, not how
many articles there are. Both measured it on one corpus, where the two
explanations cannot be told apart: every term that is rare there is rare in a
corpus of that one size.

Building the same corpus at four sizes separates them, and the answer is that
both are true at once:

    a question costs 1,910 + 37 * pages + 85 * documents touched

Only the middle term knows how large the corpus is, and it is paid whatever is
asked - both passes still walk the page table to decide which pages to skip,
and there is one page per 256 articles however empty they are. At the card's
502,016-article limit that floor is about 74,000 instructions a query.

## How far any of this is from the machine's limit

`buildwikibin.max_docs` puts a search card at 502,016 articles. The generator
stops at **37,558 people** - and not because the silo fills up. The last
cohort is born in year 220, `NOW` is 220, and `populate` refuses rather than
housing people who have not been born yet. The dwellings would have run out
too, at around 57,500, so there are two walls and the calendar is the near one.

Both are an order of magnitude below the card. The number to take from this is
not where the card breaks - `tests/test_wikisearch.py` pins that - but that
this corpus cannot reach it, and a corpus that could would have to be authored
or generated by something other than `generate.py`.
"""

from __future__ import annotations

import argparse
import contextlib
import io
import shutil
import statistics
import sys
import tempfile
import time
from pathlib import Path
from random import Random

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))
sys.path.insert(0, str(Path(__file__).resolve().parent))

import generate
import schema

import benchwiki
import buildwikibin
import buildwikisearch
import libsearch

#: Sizes to build at. The top one is just under where `populate` refuses, so
#: the sweep spans 7x and ends against the generator's own wall.
PEOPLE = (5_000, 10_000, 20_000, 37_000)

#: A term no corpus contains, so its cost is the price of being told no - the
#: floor every other query is measured against.
ABSENT = "zzqqxx"

#: How many documents the "rare" probe should touch, at every size. Holding the
#: posting count fixed is the whole experiment: if cost tracked corpus size,
#: this column would climb anyway.
RARE_DOCS = 3

#: How many rare terms to average over. One is not enough: a term is a set of
#: trigrams before it is a posting list, so two words touching three documents
#: each still differ by a few thousand instructions, and at these sizes that is
#: the same order as the effect being looked for.
RARE_TERMS = 5


def build_card(people: int, seed: int, out: Path) -> tuple[libsearch.Index, Path]:
    """Generate a silo of `people` and lay a search card over it.

    No `--relations`, so no classifier and no torch: the questions here are
    about the index, and the oracle is measured by `benchcard.py`.
    """
    db_path = out / f"silo-{people}.db"
    stem = out / f"SILO{people}"
    # `load_corpus` and `save` report to stdout for a person running a build.
    # Here they would land in the middle of the table.
    with contextlib.redirect_stdout(io.StringIO()):
        world = generate.populate(Random(seed), seed, people)
        db = schema.connect(db_path, migrate=True)
        generate.write(db, world, seed)
        db.close()

        titles, leads, aliases = buildwikisearch.load_corpus(
            db_path, schema.SOURCE, None)
        index = libsearch.build(titles, leads, aliases)

        libsearch.write_index(index, stem.with_suffix(".IDX"))
        libsearch.write_text(index, stem.with_suffix(".DAT"))
        builder = buildwikibin.build(index.num_docs,
                                     stem.with_suffix(".IDX").name,
                                     stem.with_suffix(".DAT").name)
        builder.save(str(stem.with_suffix(".bin")))
    db_path.unlink()
    return index, stem


def probes(index: libsearch.Index, seed: int) -> tuple[list[str], str, int]:
    """`RARE_TERMS` words at `RARE_DOCS` documents, and the widest term there is.

    Chosen from the index rather than written down, because a name that is rare
    in a silo of five thousand is not rare in one of thirty-seven thousand, and
    fixing the *word* would measure the corpus rather than the tiering.

    Sampled rather than taken in order, which is not fussiness. The first five
    terms alphabetically are `11000`, `11030`, `11100`, `11130`, `11200` - five
    addresses of the same length and shape, which cost the same to the
    instruction and report a spread of zero. A sample gets surnames and given
    names in too, and the spread it reports is the real one.
    """
    counts = {term: len(posts) for term, posts in index.postings.items()}
    candidates = sorted(t for t in counts if counts[t] == RARE_DOCS)
    rare = Random(seed).sample(candidates, min(RARE_TERMS, len(candidates)))
    common = max(counts, key=lambda t: (counts[t], t))
    return rare, common, counts[common]


def measure(stem: Path, query: str) -> int:
    binary, files = benchwiki.card_files(stem)
    instructions, _io, _secs, _text = benchwiki.run(binary, files, query)
    return instructions


def sweep(sizes: tuple[int, ...], seed: int, out: Path) -> None:
    ceiling = buildwikibin.max_docs(
        buildwikibin.fixed_bytes(1, len(buildwikibin.build(1).code)))
    print(f"a search card tops out at {ceiling:,} articles\n")

    header = (f"{'people':>8} {'articles':>9} {'IDX MB':>7} {'DAT MB':>7} "
              f"{'acc KB':>7} {'ceiling':>8}   "
              f"{'absent':>8} {'rare +/-':>17} {'common':>9} {'docs':>7} "
              f"{'per doc':>8}")
    print(header)
    print("-" * len(header))

    for people in sizes:
        started = time.monotonic()
        index, stem = build_card(people, seed, out)
        rare_terms, common_term, common_docs = probes(index, seed)
        absent = measure(stem, ABSENT)
        rare = [measure(stem, term) for term in rare_terms]
        common = measure(stem, common_term)
        idx_mb = stem.with_suffix(".IDX").stat().st_size / 1e6
        dat_mb = stem.with_suffix(".DAT").stat().st_size / 1e6
        print(f"{people:>8,} {index.num_docs:>9,} {idx_mb:>7.1f} {dat_mb:>7.1f} "
              f"{index.num_docs / 1024:>7.1f} {index.num_docs / ceiling:>7.1%}   "
              f"{absent:>8,} "
              f"{round(statistics.mean(rare)):>8,}"
              f"{round(statistics.pstdev(rare)):>+8,} "
              f"{common:>9,} {common_docs:>7,} "
              f"{(common - absent) / common_docs:>8.1f}"
              f"   {time.monotonic() - started:.0f}s", flush=True)
        for path in stem.parent.glob(f"{stem.name}.*"):
            path.unlink()

    print(f"\n'absent' is a word no corpus holds, so it is the floor. 'rare' is "
          f"the mean of\n{RARE_TERMS} words holding at exactly {RARE_DOCS} "
          f"documents, with the spread beside it. 'per doc'\nis what the "
          f"widest-scattering term costs above the floor, per document it\n"
          f"touches - the column to read if the question is whether a bigger "
          f"corpus is\na dearer one.")


def main() -> None:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--people", default=",".join(str(n) for n in PEOPLE),
                    help="comma-separated sizes to build at")
    ap.add_argument("--seed", type=int, default=18)
    ap.add_argument("--keep", type=Path,
                    help="write the cards here instead of a temporary directory")
    args = ap.parse_args()

    sizes = tuple(int(n) for n in args.people.split(","))
    out = args.keep or Path(tempfile.mkdtemp(prefix="silo-sweep-"))
    out.mkdir(parents=True, exist_ok=True)
    try:
        sweep(sizes, args.seed, out)
    finally:
        if args.keep is None:
            shutil.rmtree(out, ignore_errors=True)


if __name__ == "__main__":
    main()
